import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#120217',
  },
  mapPlaceholder: {
    height: 400,
    backgroundColor: '#F5F7FF',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 20,
    borderRadius: 16,
  },
  mapText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#120217',
    marginTop: 12,
  },
  mapSubtext: {
    fontSize: 14,
    color: '#4b5f83',
    marginTop: 4,
  },
  locationButton: {
    position: 'absolute',
    bottom: 280,
    right: 36,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  filterPanel: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  filterTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#120217',
    marginBottom: 16,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 12,
  },
  filterButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F7FF',
    paddingVertical: 12,
    borderRadius: 12,
    gap: 8,
  },
  filterButtonText: {
    fontSize: 14,
    color: '#5B6FF0',
    fontWeight: '600',
  },
});